config/routes.rb
Thingsmith::Application.routes.draw do

  resources :emails

  get "users_controller/edit"
  get "users_controller/show"
  get "users_controller/destroy"
  get "users_controller/create"

  resources :jobs do
    resources :bids do
      get 'accept'
    end
  end

  resources :bids

  resources :users

  mount Dailycred::Engine => '/auth', :as => 'dailycred_engine'

  match 'home' => 'high_voltage/pages#show', :id => 'home'

  root :to => 'jobs#index'

end

app/models/bid.rb
class Bid < ActiveRecord::Base
	attr_accessible :user_id, :job_id, :amount, :notes, :days, :accepted

	belongs_to :job

	validates :amount, :presence => true
	validates :notes, :allow_blank => true,
		:length => { :maximum => 140 }
	validates :days, :numericality => { :only_integer => true }
end

app/models/email.rb
class Email < ActiveRecord::Base
  attr_accessible :email

  validates :email, :presence => true,
   :uniqueness => true,
   :email => true
end

app/models/job.rb
class Job < ActiveRecord::Base
	attr_accessible :name, :dimension_x, :dimension_y, :thickness, :material, :completion_date, :budget, :file_url, :complete

	MATERIALS = { '1/8in Plywood' => 1, '1/4in Plywood' => 2, 'Premium Human Poop' => 3 }

	belongs_to :user

	has_many :bids, :dependent => :destroy

	validates :name, :presence => true,
		:length => { :minimum => 6, :maximum => 30 }
	validates :dimension_x, :presence => true
	validates :dimension_y, :presence => true
	validates :budget, :presence => true

	def owns_job(user)
		return (self.user and self.user == user)
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Gravtastic
  gravtastic

  has_many :jobs

  attr_accessible :city, :bio

  validates :bio, :allow_blank => true,
    :length => { :maximum => 140 }
  validates :city, :allow_blank => true,
    :length => { :minimum => 3, :maximum => 30 }

  acts_as_dailycred
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def require_login
    unless logged_in?
      redirect_to connect_path( :identity_provider => :dailycred)
    end
  end

  def logged_in?
    !!current_user
  end

  if !config.consider_all_requests_local && Rails.env.production?
    rescue_from Exception, :with => :render_error
    rescue_from ActiveRecord::RecordNotFound, :with => :render_not_found
    rescue_from ActionController::RoutingError, :with => :render_not_found
    rescue_from ActionController::UnknownController, :with => :render_not_found
  end

  def render_error
    render :template => 'errors/500', :status => 500
  end

  def render_not_found
    render :template => 'errors/404', :status => 400
  end

  private

  def current_user
    begin
      @current_user || User.find(session[:user_id]) if session[:user_id]
    rescue
      nil
    end
  end

  protect_from_forgery
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  before_filter :require_login, :only => [:create, :new, :edit, :update, :destroy, :accept]

  def show
    @bid = Bid.find(params[:id])
  end

  def new
    @bid = Bid.new
    @bid.job_id = params['job_id']
  end

  def create
    if current_user
      @job = Job.find(params[:bid][:job_id])
      @bid = @job.bids.create(params[:bid])
      @bid.user_id = current_user.id
      if @bid.save
        redirect_to job_path(@job), :notice => "Successfully created bid."
      else
        render :action => 'new'
      end
    else
      redirect_to home_path, :notice => "Please log in."
    end
  end

  def edit
    @bid = Bid.find(params[:id])
  end

  def update
    @bid = Bid.find(params[:id])
    if @bid.update_attributes(params[:bid])
      redirect_to @bid, :notice  => "Successfully updated bid."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @bid = Bid.find(params[:id])
    @bid.destroy
    redirect_to bids_url, :notice => "Successfully destroyed bid."
  end

  def accept
    @bid = Bid.find(params[:bid_id])
    @job = @bid.job

    if @bid.update_attributes(:accepted => true) and @job.update_attributes(:complete => true)
      redirect_to @job, :notice => "Bid accepted! Your order will be created and shipped to you soon."
    else
      redirect_to @job, :notice => "Failed to accept bid. Please try again."
    end
  end
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  def new
    @email = Email.new
  end

  def create
    @email = Email.new(params[:email])
    if @email.save
      redirect_to root_url, :notice => "Congrats. We'll email " + @email.email + " with updates about ThingSmith."
    else
      redirect_to root_url, :notice => "Something went wrong. Make sure you entered a valid email and that you aren't on the list already."
    end
  end

  def destroy
    @email = Email.find(params[:id])
    @email.destroy
    redirect_to root_url, :notice => "Successfully destroyed email."
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_filter :require_login, :only => [:create, :new, :edit, :update, :destroy]

  def index
    @jobs = Job.all
  end

  def show
    @job = Job.find(params[:id])
    @admin = (current_user and @job.user and @job.user == current_user)
  end

  def new
    if current_user
      @job = Job.new
    else
      redirect_to root_path, :notice => "Please sign in."
    end
  end

  def create
    if current_user
      @job = current_user.jobs.create(params[:job])
      if @job.save
        redirect_to @job, :notice => "Successfully created job."
      else
        render :action => 'new'
      end
    else
      redirect_to root_path, :notice => "Please sign in."
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    if @job.update_attributes(params[:job])
      redirect_to @job, :notice  => "Successfully updated job."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to jobs_url, :notice => "Successfully destroyed job."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_login, :only => [:edit, :update]

  def edit
  	@user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to @user, :notice  => "Successfully updated user."
    else
      render :action => 'edit'
    end
  end

  def show
    if params[:id]
    	@user = User.find(params[:id])
    elsif current_user
      @user = current_user
    else
      redirect_to root_path
    end
  end
end

app/controllers/users_controller_controller.rb
class UsersControllerController < ApplicationController
  def edit
  end

  def show
  end

  def destroy
  end

  def create
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/users_controller_helper.rb
module UsersControllerHelper
end

app/views/bids/_bid.html.haml
- @user = User.find(bid.user_id)
- @job = Job.find(bid.job_id)

.well
	.row
		.span2{ :style => 'text-align: center;' }
			%a{ :href => user_path(@user) }
				= image_tag @user.gravatar_url, :class => 'img-circle', :style => 'margin-bottom: 10px;'
			
			%small.muted
				%i
					%a{ :href => 'mailto:' + @user.email + '?subject=' + @job.name.html_safe }
						= @user.email
		
		.span8
			%h1
				$
				= bid.amount
				in
				= bid.days
				days

			%p
				= bid.notes

			- if !@job.complete and @admin
				= link_to 'Accept Bid &raquo;'.html_safe, job_path(@job) + '/bids/' + bid.id.to_s() + '/accept', :class => 'btn btn-primary'
		

app/views/bids/_form.html.haml
.row{ :style => 'text-align: center;' }
	= form_for(@bid) do |f|
		.span4.offset4
			= f.error_messages

			%p
				= f.label :amount, 'Price (USD)'
				= f.text_field :amount
			%p
				= f.label :notes, 'What Makes you so Special?'
				= f.text_area :notes, :rows => 4
			%p
				= f.label :days, 'Days to Complete'
				= f.text_field :days
			%p
				= f.text_field :job_id, :placeholder => 'hello', :style => "position: absolute; top: -1000px;"
			%p
				= f.submit 'Make a Bid &raquo;'.html_safe, :class => 'btn btn-primary btn-large'

app/views/bids/edit.html.haml
= render 'form'

%p
  = link_to "Show", @bid
  |
  = link_to "View All", bids_path

app/views/bids/new.html.haml
= render 'form'

app/views/bids/show.html.haml
= render @bid

app/views/jobs/_form.html.haml
.row{ :style => 'text-align: center;' }
  = form_for @job do |f|
    .span4.offset4
      = f.error_messages
      %p
        = f.label :name, 'Name of your Project'
        = f.text_field :name
      %p
        = f.label :dimension_x, 'Approximate Width (in inches)'
        = f.text_field :dimension_x
      %p
        = f.label :dimension_y, 'Approximate Height (in inches)'
        = f.text_field :dimension_y
      %p
        = f.label :material, 'Material'
        = f.select(:material, Job::MATERIALS)
      %p
        = f.label :completion_date, 'Completion Date'
        = f.date_select :completion_date
      %p
        = f.label :budget, 'Approximate Budget'
        = f.text_field :budget
      %p
        = f.label :file_url
        = f.filepicker_field :file_url, :options => { :button_class => 'btn', :mimetypes => "image/png,image/svg" }
      %p
        = f.submit 'Make a Model &raquo;'.html_safe, :class => 'btn btn-primary btn-large'

app/views/jobs/_job.html.haml
.well
	.row
		.span2{ :style => 'text-align: center' }
			%img{ :src => job.file_url, :style => 'border-radius: 5px; width: 128px; height: 128px;' }

		.span9
			%h3
				= link_to job.name, job_path(job)

				%small.muted
					by
					%a{ :href => user_path(job.user) }
						= job.user.email

			%p
				%strong
					= job.dimension_x
				inches by
				%strong
					= job.dimension_y
				inches

				%br
				
				requested for 
				%strong
					$
					= job.budget

				%br

				must be done by 
				%strong
					= job.completion_date

app/views/jobs/edit.html.haml
= render 'form'

%p
  = link_to "Show", @job
  |
  = link_to "View All", jobs_path

app/views/jobs/index.html.haml
= render 'layouts/hero'

%h3.indent
	jobs

= render Job.all

app/views/jobs/new.html.haml
= render 'form'

%p= link_to "Back to List", jobs_path

app/views/jobs/show.html.haml
- if @job.complete
	= render :partial => 'layouts/notice', :locals => { :message => 'This job has already been completed.' }

= render @job

%h3.indent
	bids
	.pull-right
		= link_to "make a bid &raquo;".html_safe, new_job_bid_path(@job) + '?job_id=' + @job.id.to_s()

= render @job.bids

app/views/layouts/_footer.html.haml
.row.right.muted
	.span3
		%h6
			The Team
		%small
			%a{ :href => '//github.com/aaasen' } Lane Aasen
			%br
			George Matter
			%br
			Michael Rosenberger
	
	.span3
		%h6
			Contact Us
		%small
			%a{ :href => 'mailto:thingsmithus@gmail.com' } thingsmithus@gmail.com

	.span3
		%h6
			Contribute
		%small
			%a{ :href => '//aaasen.github.com/thingsmith'} View on Github

	.span3
		%small
			Made in Seattle

			%br

			%i.icon-heart
			StudentRND

app/views/layouts/_hero.html.haml
.hero-unit
	%h2		
		%b
			have a laser cutter?
		click on jobs to make offers.

		%br

		%b
			need something cut?
		%a{ :href => new_job_path }>make a new job.

		= render :partial => 'emails/new'

app/views/layouts/_navbar.html.haml
.navbar
	.navbar-inner
		%a.bold.brand{ :href => root_path }
			%b ThingSmith
			
			%small{ :style => 'margin-left: 4px;'}
				a community of makers
		.pull-right
			- if current_user
				%a.bold.brand{ :href => user_path(current_user) }
					%b My Profile
				%a.bold.brand{ :href => dailycred_engine.logout_path }
					%b Sign Out
			- else
				%a.bold.brand{ :href => '/auth/dailycred' }
					%b Login
				%a.bold.brand{ :href => '/auth/dailycred' }
					%b Sign Up
			%a.bold.brand{ :href => '/jobs' }
				%b All Jobs
			%a.bold.brand{ :href => '/jobs/new' }
				%b New Job
		

app/views/layouts/_notice.html.haml
.alert.center
	%strong Hey!

	-if message
		= message

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
	%head
		%title Thingsmith
		= stylesheet_link_tag    "application", :media => "all"
		= javascript_include_tag "application"
		= csrf_meta_tags
		= filepicker_js_include_tag
	%body
		.container
			= render 'layouts/navbar'

			- if flash[:notice]
				.alert{ :style => 'text-align: center;'}
					%strong
						Hey!
					= flash[:notice]

			= yield

			= render 'layouts/footer'

app/views/users/_form.html.haml
.row{ :style => 'text-align: center;' }
	= form_for(@user) do |f|
		.span4.offset4
			= f.error_messages

			%p
				= f.label :bio, 'Miniature Bio'
				= f.text_area :bio, :rows => 8
			%p
				= f.label :city, 'Which City do you Live in?'
				= f.text_field :city
			%p
				Update your profile picture at
				%a{ :href => 'http://gravatar.com/' } Gravatar
			
			= f.submit 'Update Profile &raquo;'.html_safe, :class => 'btn btn-primary btn-large'

app/views/users/_user.html.haml
.well
	.row
		.span2{ :style => 'text-align: center;' }
			= image_tag user.gravatar_url, :class => 'img-circle', :style => 'margin-bottom: 10px;'
			
			- if current_user and current_user == user
				= link_to 'Edit Profile', edit_user_path(current_user), :class => 'btn'
		
		.span9
			%h4
				= user.email
				-if user.city
					from
					= user.city
			-if user.bio
				%p
					= user.bio

app/views/users/create.html.haml
<h1>UsersController#create</h1>
<p>Find me in app/views/users_controller/create.html.erb</p>

app/views/users/destroy.html.haml
<h1>UsersController#destroy</h1>
<p>Find me in app/views/users_controller/destroy.html.erb</p>

app/views/users/edit.html.haml
= render 'form'

app/views/users/show.html.haml
= render @user

%h3.indent
	creations

= render @user.jobs

app/views/users_controller/create.html.erb
<h1>UsersController#create</h1>
<p>Find me in app/views/users_controller/create.html.erb</p>

app/views/users_controller/destroy.html.erb
<h1>UsersController#destroy</h1>
<p>Find me in app/views/users_controller/destroy.html.erb</p>

app/views/users_controller/edit.html.erb
<h1>UsersController#edit</h1>
<p>Find me in app/views/users_controller/edit.html.erb</p>